apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-order
  labels:
    app: tech-challenge-order
spec:
  template:
    metadata:
      name: tech-challenge-order
      labels:
        app: tech-challenge-order
    spec:
      containers:
        - name: tech-challenge-order-api
          image: 637423603914.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-order-secret
                  key: DATABASE_URL
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-order-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-order-secret
                  key: PASSWORD
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-order