apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-order-service
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30004