version: '3.7'
services:
  account-service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: api
    container_name: account-service
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432